# Generated by Django 5.0.4 on 2024-04-08 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activite', '0002_activite_groupe_alter_activite_candidat_and_more'),
        ('groupe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiviteGroupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('activite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activite.activite')),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groupe.groupe')),
            ],
        ),
    ]
