# Generated by Django 5.0.4 on 2024-04-13 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('critere', '0002_critere_typecritere'),
        ('note', '0002_alter_activitegroupe_groupe'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitegroupe',
            name='critere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='critere.critere'),
        ),
    ]
