# Generated by Django 5.0.4 on 2024-04-13 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('critere', '0003_critere_activite'),
        ('note', '0003_activitegroupe_critere'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitegroupe',
            name='critere',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='critere.critere'),
        ),
    ]
