# Generated by Django 5.0.4 on 2024-04-13 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0004_alter_activitegroupe_critere'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitegroupe',
            name='activite',
        ),
    ]
