# Generated by Django 5.0.4 on 2024-04-13 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0005_remove_activitegroupe_activite'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitegroupe',
            name='val',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
    ]
