# Generated by Django 5.0.4 on 2024-04-13 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0006_activitegroupe_val'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitegroupe',
            name='val',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
