# Generated by Django 5.0.4 on 2024-04-08 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidat', '0001_initial'),
        ('jury', '0001_initial'),
        ('media', '0001_initial'),
        ('sponsor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomactivite', models.CharField(blank=True, default='', max_length=100)),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formulaires', to='candidat.candidat')),
                ('jury', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formulaires', to='jury.jury')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formulaires', to='media.media')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formulaires', to='sponsor.sponsor')),
            ],
        ),
    ]
