# Generated by Django 5.0.4 on 2024-04-08 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activite', '0001_initial'),
        ('candidat', '0001_initial'),
        ('groupe', '0001_initial'),
        ('jury', '0001_initial'),
        ('media', '0001_initial'),
        ('sponsor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activite',
            name='groupe',
            field=models.ManyToManyField(blank=True, related_name='activite', to='groupe.groupe'),
        ),
        migrations.AlterField(
            model_name='activite',
            name='candidat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidat', to='candidat.candidat'),
        ),
        migrations.AlterField(
            model_name='activite',
            name='jury',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jury', to='jury.jury'),
        ),
        migrations.AlterField(
            model_name='activite',
            name='media',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='media.media'),
        ),
        migrations.AlterField(
            model_name='activite',
            name='sponsor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsor', to='sponsor.sponsor'),
        ),
    ]
