# Generated by Django 5.0.4 on 2024-04-08 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activite', '0002_activite_groupe_alter_activite_candidat_and_more'),
        ('candidat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activite',
            name='candidat',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidat', to='candidat.candidat'),
        ),
    ]
