# Generated by Django 5.0.4 on 2024-06-29 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

def set_default_organisateur(apps, schema_editor):
    Activite = apps.get_model('activite', 'Activite')
    CustomUser = apps.get_model('autentication', 'CustomUser')
    default_user = CustomUser.objects.first()
    if default_user:
        Activite.objects.filter(organisateur__isnull=True).update(organisateur=default_user)


class Migration(migrations.Migration):

    dependencies = [
        ('activite', '0005_alter_activite_organisateur'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='activite',
            name='organisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activites', to='autentication.customuser'),
        ),
        migrations.RunPython(set_default_organisateur),
    ]
