# Generated by Django 5.0.4 on 2024-07-25 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activite', '0006_alter_activite_organisateur'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='activite',
            name='candidat',
        ),
        migrations.RemoveField(
            model_name='activite',
            name='jury',
        ),
        migrations.RemoveField(
            model_name='activite',
            name='media',
        ),
        migrations.AlterField(
            model_name='activite',
            name='sponsor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='activite.sponsorreference'),
        ),
    ]
