# Generated by Django 5.0.4 on 2024-08-19 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activite', '0007_sponsorreference_remove_activite_candidat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activite',
            name='sp_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
