# Generated by Django 5.0.4 on 2024-08-19 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activite', '0009_remove_activite_sp_id_activite_sp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activite',
            name='sponsor',
        ),
        migrations.RemoveField(
            model_name='activite',
            name='sp',
        ),
        migrations.AddField(
            model_name='activite',
            name='sponsor_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='SponsorReference',
        ),
    ]
