# Generated by Django 5.0.4 on 2024-09-03 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activite', '0012_remove_sponsor_updated_at_remove_sponsor_website_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activite',
            name='sponsor',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='activite.sponsor'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
