# Generated by Django 5.0.4 on 2024-09-03 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activite', '0013_alter_activite_sponsor_alter_sponsor_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activite',
            name='sponsor',
        ),
        migrations.AddField(
            model_name='activite',
            name='sponsor',
            field=models.ManyToManyField(blank=True, default='', null=True, to='activite.sponsor'),
        ),
    ]
