# Generated by Django 5.0.4 on 2024-09-03 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activite', '0014_remove_activite_sponsor_activite_sponsor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activite',
            name='sponsor',
        ),
        migrations.AddField(
            model_name='activite',
            name='sponsor',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='activite.sponsor'),
        ),
    ]
