# Generated by Django 5.0.4 on 2024-04-08 14:58

import sponsor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomsponsor', models.CharField(blank=True, default='', max_length=100)),
                ('logo', models.ImageField(blank=True, default='', null=True, upload_to=sponsor.models.upload_path)),
            ],
        ),
    ]
