# Generated by Django 5.0.4 on 2024-06-29 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsor',
            name='logo',
        ),
    ]
