# Generated by Django 5.0.4 on 2024-07-12 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0002_remove_sponsor_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='logo',
            field=models.ImageField(blank=True, default='', null=True, upload_to='sponsor_logos/'),
        ),
    ]
