# Generated by Django 5.0.4 on 2024-09-03 10:49

import sponsor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0003_sponsor_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='logo',
            field=models.ImageField(blank=True, default='', null=True, upload_to=sponsor.models.upload_path),
        ),
    ]
