# Generated by Django 5.0.4 on 2024-04-08 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groupe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, default='', max_length=100)),
                ('prenom', models.CharField(blank=True, default='', max_length=100)),
                ('created', models.DateField(auto_now_add=True)),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidats', to='groupe.groupe')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
