# Generated by Django 5.0.4 on 2024-06-29 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidat', '0001_initial'),
        ('groupe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidat',
            name='groupe',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='candidats', to='groupe.groupe'),
        ),
    ]
