# Generated by Django 5.0.4 on 2024-09-03 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidat', '0002_alter_candidat_groupe'),
        ('groupe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidat',
            name='groupe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidats', to='groupe.groupe'),
        ),
    ]
