# Generated by Django 5.0.4 on 2024-06-29 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('OR', 'Organisateur'), ('JU', 'Jury'), ('JP', 'Jury Populaire')], default='OR', max_length=2),
        ),
    ]
